config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
  }
  resource :customers, only: [:edit, :update]
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  root to: "homes#top"
  get '/about' => 'homes#about', as: 'about'
  get '/customers/my_page' => 'customers#show'
  get '/customers/caution' => 'customers#caution'
  put '/customers/hide' => 'customers#hide',as: "customers_hide"
  resources :items, only: [:index, :show]
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/thanks' => 'orders#thanks'
  resources :orders, only: [:new, :create, :show, :index]
  resources :addresses, except: [:new, :show]

  namespace :admin do
    resources :items, except: :destroy
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    patch '/order_items/:id' => 'order_items#update', as: 'make_status'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :items, through: :cart_items

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :tel_number, presence: true

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < Admin::AdminApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :tel_number, :email, :is_deleted)
  end

end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: [:create]

  protected

  def reject_user
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if (@customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == true))
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def show
    @customer = current_customer
  end

  def edit
    @customer = current_customer
  end

  def update
    @customer = current_customer
    @customer.update(customer_params)
    redirect_to customers_my_page_path
  end

  def caution
    @customer = current_customer
  end

  def hide
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end


  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :tel_number, :email)
  end
end

app/views/customers/caution.html.erb
<div class="customer_body">
  <div class="caution_container d-flex align-items-center justify-content-center">
    <div class="d-flex flex-column">
      <p class="text-center font-weight-bold">本当に退会しますか？</p>
      <p class="text-center">
        退会すると、会員登録情報や<br />
        これまでの購入履歴が閲覧できなくなります。<br />
        退会する場合は、「退会する」をクリックしてください。
      </p>
      <div class="d-flex justify-content-center">
        <%= link_to '退会しない', customers_my_page_path, class:"btn btn-sm btn-primary mx-2" %>
        <%= link_to '退会する', customers_hide_path(current_customer), method: :put, data: {confirm: "削除しますか？"}, class:"btn btn-sm btn-danger mx-3" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<div class="customer_body">
  <div class="container">
    <div class="row py-5">
      <div class="col-12" style="height: 500px">
        <h4 class="customer_edit_heading">会員情報編集</h4>

        <%= form_with url: customers_path, model: @customer, local: true do |f| %>
          <div class="form-group mt-4">
            <%= f.label :'氏名', class:"col-2 label_text" %>
            <%= f.text_field :last_name, class:"mr-3" %>
            <%= f.text_field :first_name %>
          </div>
          <div class="form-group">
            <%= f.label :'フリガナ', class:"col-2 label_text" %>
            <%= f.text_field :last_name_kana, class:"mr-3" %>
            <%= f.text_field :first_name_kana %>
          </div>
          <div class="form-group">
            <%= f.label :'郵便番号', class:"col-2 label_text" %>
            <%= f.text_field :postal_code %>
          </div>
          <div class="form-group">
            <%= f.label :'住所', class:"col-2 label_text" %>
            <%= f.text_field :address, class:"col-7" %>
          </div>
          <div class="form-group">
            <%= f.label :'電話番号', class:"col-2 label_text" %>
            <%= f.text_field :tel_number %>
          </div>
          <div class="form-group">
            <%= f.label :'メールアドレス', class:"col-2 label_text" %>
            <%= f.text_field :email %>
          </div>
          <div class="d-flex pt-3">
            <div class="col-3 offset-2 p-0">
              <%= f.button :type => 'submit', class:"btn btn-sm btn-success shadow col-8" do %>
                <i class="fas fa-user-edit mr-2"></i>編集内容を保存
              <% end %>
            </div>
            <div class="col-2 p-0">
              <%= link_to customers_caution_path, class:"btn btn-sm btn-danger shadow" do %>
                <i class="fas fa-user-slash mr-2"></i>退会する
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="customer_body">
  <div class="container">
    <div class="row py-3">
      <div class="col-11 mx-auto">
        <h3 class="customer_heading">My Page</h3>

        <div class="d-flex mt-3">
          <h5 class="font-weight-bold p-1 mr-3 mb-0">登録情報</h5>
          <%= link_to  edit_customers_path, class:"btn btn-sm btn-success shadow mx-3 pt-2" do %>
            <i class="fas fa-user-cog mr-2 mb-1"></i>編集する
          <% end %>
        </div>

        <table class="col-7 table table-bordered mt-3 customer_table shadow">
          <tr>
            <th class="table-secondary">氏名</td>
            <td class="table-light"><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
          <tr>
            <th class="table-secondary">カナ</td>
            <td class="table-light"><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <th class="table-secondary">郵便番号</td>
            <td class="table-light"><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <th class="table-secondary">住所</td>
            <td class="table-light"><%= @customer.address %></td>
          </tr>
          <tr>
            <th class="table-secondary">電話番号</td>
            <td class="table-light"><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <th class="table-secondary">メールアドレス</td>
            <td class="table-light"><%= @customer.email %></td>
          </tr>
        </table>

        <div class="d-flex col-5 p-0 my-3">
          <h5 class="font-weight-bold p-1 mr-5 mb-0">配送先　</h5>
          <%= link_to addresses_path, class:"btn btn-sm btn-primary shadow" do %>
            <i class="fas fa-mail-bulk mr-2"></i>一覧を見る
          <% end %>
        </div>

        <div class="d-flex col-5 p-0">
          <h5 class="font-weight-bold p-1 mr-5 mb-0">注文履歴</h5>
          <%= link_to orders_path, class:"btn btn-sm btn-primary shadow" do %>
            <i class="far fa-list-alt mr-2"></i>一覧を見る
          <% end %>
      </div>
    </div>
  </div>
</div>