config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, controllers: {
  sessions:      'admin/sessions',
  passwords:     'admin/passwords',
  registrations: 'admin/registrations'
  }
  resource :customers, only: [:edit, :update]
  devise_for :customers, controllers: {
    sessions:      'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  root to: "homes#top"
  get '/about' => 'homes#about', as: 'about'
  get '/customers/my_page' => 'customers#show'
  get '/customers/caution' => 'customers#caution'
  put '/customers/hide' => 'customers#hide',as: "customers_hide"
  resources :items, only: [:index, :show]
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, only: [:index, :update, :destroy, :create]
  post '/orders/confirm' => 'orders#confirm'
  get '/orders/thanks' => 'orders#thanks'
  resources :orders, only: [:new, :create, :show, :index]
  resources :addresses, except: [:new, :show]

  namespace :admin do
    resources :items, except: :destroy
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    patch '/order_items/:id' => 'order_items#update', as: 'make_status'
  end
end

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <h3 class="text-danger"><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
  <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li class="text-danger"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-dark text-white pt-4 pb-4" style="height: 180px;">
  <div class="container">
    <div class="row no-gutters">
      <div class="col-2 offset-1">
        <div class="footer_round mt-3">
          <img class="footer_logo" src=<%= asset_path('1.png') %> width="110" height="70">
        </div>
      </div>
      <div class="col-4">
        <h6 class="footer_text text-white mt-2 mb-3">Information</h6>
        <ul class="p-0 list-unstyled">
          <li>
            <p class="text-white-50">Open: 10:00 ~ 19:00</p>
          </li>
          <li>
            <p class="text-white-50">Close: Monday,Tuesday</p>
          </li>
        </ul>
      </div>
      <div class="col-4">
        <h6 class="footer_text text-white mt-2 mb-2 ">Address</h6>
        <ul class="p-0 list-unstyled">
          <li>
            <p class="text-white-50 mb-2">〒380-8570</p>
          </li>
          <li>
            <p class="text-white-50 mb-2">長野県長野市大字南長野字幅下692-2</p>
          </li>
          <li>
            <p class="text-white-50 mb-2">Tel:026-232-0111</p>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/f8d37013c4.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header class='bg-header'>
      <nav class='navbar navbar-expand-md' style='height: 140px'>
        <div class='container'>
          <a href="/">
            <img class="header-logo" src=<%= asset_path('1.png') %> width="180" height="120">
          </a>
          <% if customer_signed_in? %>
            <% unless current_page?(new_admin_session_path) %>
              <span class='text-body font-weight-bold'>ようこそ、<%= @customer.last_name %>さん !</span>
            <% end %>
          <% end %>
          <div>
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <li><%= link_to 'マイページ', customers_my_page_path, class:'nav-link text-body font-weight-bold mr-1' %></li>
                <li><%= link_to '商品一覧', items_path, class:'nav-link text-body font-weight-bold mr-1' %></li>
                <li><%= link_to 'カート', cart_items_path, class:'nav-link text-body font-weight-bold mr-1' %></li>
                <li><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class:'nav-link text-body font-weight-bold' %></li>
              <% elsif admin_signed_in? %>
                <li><%= link_to '商品一覧', admin_items_path, class:'nav-link text-body font-weight-bold' %></li>
                <li><%= link_to '会員一覧', admin_customers_path, class:'nav-link text-body font-weight-bold' %></li>
                <li><%= link_to '注文履歴一覧', admin_orders_path, class:'nav-link text-body font-weight-bold' %></li>
                <li><%= link_to 'ジャンル一覧', admin_genres_path, class:'nav-link text-body font-weight-bold' %></li>
                <li><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:'nav-link text-dark font-weight-bold' %></li>
              <% else %>
                <li><%= link_to 'about', about_path, class:'nav-link text-body font-weight-bold mr-1' %></li>
                <li><%= link_to '商品一覧', items_path, class:'nav-link text-body font-weight-bold mr-1' %></li>
                <li><%= link_to '新規登録', new_customer_registration_path, class:'nav-link text-body font-weight-bold mr-1' %></li>
                <li><%= link_to 'ログイン', new_customer_session_path, class:'nav-link text-body font-weight-bold' %></li>
              <% end %>
            </ul>
            <div class='mt-2'>
              <%= form_with url: items_path, method: :get, local:true do |f| %>
                <div class='col-8 offset-4 border d-flex px-0 bg-white'>
                  <%= f.text_field :content, placeholder: 'Search', class:'border-0 col-10' %>
                  <%= f.submit "\uf002", style:'font-family: FontAwesome', class:'btn btn-default text-primary col-2 px-0 py-1' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <%= yield %>
    <%= render 'layouts/footer' %>
    </main>
  </body>
</html>